# docker-compose.test.yml - The Brothers Barber Shop Testing Environment
# Isolated testing environment with test database

version: '3.8'

services:
  # Backend Test Service
  backend-test:
    build:
      context: ./backend
      target: development
    container_name: barbershop-backend-test
    environment:
      - NODE_ENV=test
      - PORT=5001
      - MONGODB_URI=mongodb://mongo-test:27017/barbershop_test
      - JWT_SECRET=test_jwt_secret_key_for_testing_only
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=1d
      - CLOUDINARY_CLOUD_NAME=test
      - CLOUDINARY_API_KEY=test
      - CLOUDINARY_API_SECRET=test
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - barbershop-test-network
    depends_on:
      - mongo-test
      - redis-test
    command: npm run test:docker
    profiles:
      - test

  # Test MongoDB Service
  mongo-test:
    image: mongo:7
    container_name: barbershop-mongo-test
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpass
      - MONGO_INITDB_DATABASE=barbershop_test
    volumes:
      - mongo-test-data:/data/db
    networks:
      - barbershop-test-network
    profiles:
      - test

  # Test Redis Service
  redis-test:
    image: redis:7-alpine
    container_name: barbershop-redis-test
    command: redis-server --appendonly yes --maxmemory 128mb
    volumes:
      - redis-test-data:/data
    networks:
      - barbershop-test-network
    profiles:
      - test

  # Integration Test Runner
  integration-tests:
    build:
      context: ./backend
      target: development
    container_name: barbershop-integration-tests
    environment:
      - NODE_ENV=test
      - API_BASE_URL=http://backend-test:5001/api
      - MONGODB_URI=mongodb://mongo-test:27017/barbershop_test
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./test-results:/app/test-results
    networks:
      - barbershop-test-network
    depends_on:
      - backend-test
    command: npm run test:integration
    profiles:
      - integration-test

  # End-to-End Test Runner
  e2e-tests:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    container_name: barbershop-e2e-tests
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://backend-test:5001/api
      - CYPRESS_BASE_URL=http://frontend-test:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./e2e-results:/app/cypress/videos
      - ./e2e-results:/app/cypress/screenshots
    networks:
      - barbershop-test-network
    depends_on:
      - backend-test
      - frontend-test
    command: npm run test:e2e:docker
    profiles:
      - e2e-test

  # Frontend Test Service (for E2E)
  frontend-test:
    build:
      context: ./frontend
      target: development
    container_name: barbershop-frontend-test
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://backend-test:5001/api
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - barbershop-test-network
    command: npm run dev -- --host 0.0.0.0 --port 3001
    profiles:
      - e2e-test

volumes:
  mongo-test-data:
    driver: local
  redis-test-data:
    driver: local

networks:
  barbershop-test-network:
    driver: bridge
    name: barbershop-test-network