# =====================================================
# RENDER DEPLOYMENT CONFIGURATION
# =====================================================
# 
# 📋 CONFIGURACIÓN PARA RENDER.COM
# Este archivo define el servicio backend en Render
# 
# 🚀 INSTRUCCIONES DE DEPLOY:
# 1. Crear cuenta en render.com
# 2. Conectar repositorio GitHub 
# 3. Usar esta configuración automáticamente
# =====================================================

services:
  # Backend API Service
  - type: web
    name: barbershop-api
    env: node
    region: oregon  # Cambiar según tu ubicación
    plan: starter   # Plan gratuito por 90 días, luego $7/mes
    
    # Build Configuration
    buildCommand: |
      echo "🔧 Instalando dependencias..."
      cd backend
      npm ci --only=production
      echo "✅ Build completado"
    
    # Start Command
    startCommand: |
      echo "🚀 Iniciando servidor..."
      cd backend
      npm start
    
    # Health Check
    healthCheckPath: /health
    
    # Auto Deploy
    autoDeploy: true  # Deploy automático en push a main
    
    # Environment Variables
    # IMPORTANTE: Configurar en Render Dashboard > Environment
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 10000  # Puerto que usa Render
        
      # Variables que se configuran en Render UI (no aquí):
      # MONGODB_URI - Connection string de MongoDB Atlas
      # JWT_SECRET - Secreto seguro para JWT
      # CLOUDINARY_CLOUD_NAME - Tu cloud name
      # CLOUDINARY_API_KEY - Tu API key  
      # CLOUDINARY_API_SECRET - Tu API secret
      # FRONTEND_URL - URL de Vercel una vez desplegado
      
    # Disk Storage (para logs temporales)
    disk:
      name: logs
      mountPath: /opt/render/project/src/backend/logs
      sizeGB: 1

# =====================================================
# CONFIGURACIÓN ADICIONAL
# =====================================================

# Domains (configurar después del primer deploy)
# domains:
#   - name: api.tudominio.com
#     type: apex

# Notifications (opcional)
# notifications:
#   - type: email
#     emails:
#       - tu-email@gmail.com
#     events:
#       - deploy-success
#       - deploy-failure